package planner.app;

public enum Operation {

	ACT_ASSIGN_USER, ACT_REG_HOURS, ACT_SET_END_DATE, ACT_SET_NAME, ACT_SET_START_DATE, ACT_SET_WORK_HOURS,
	PLANNER_CREATE_PROJECT, PLANNER_REGISTER_USER,
	PROJ_SET_NAME,
	USER_NULL_USERNAME, USER_REGISTER_WORK,
	WORK_SET_ACT, WORK_DATE_MISMATCH, WORK_SET_EARLY_TO_DATE, WORK_SET_LATE_FROM_DATE, WORK_SET_NULL_FROM_DATE, WORK_SET_NULL_TO_DATE

}